
[actix_web_config]
server = "0.0.0.0"
port = 9000


[postgresql_config]
server = "192.168.11.33"
port = 5432
user = "taiji"
pwd = "zhangsanfeng"
db = "taiji"


[backend_config]
host = "192.168.1.118"
port = 9000
nginx_host = "192.168.1.118"
nginx_port = 8088
images = "http://192.168.1.118:8088/images/"